### ISSUE TITLE
Database is not written to file

### ISSUE THREAD

**Issue by jacbart** [cpcharland/Charland_CSCI2270_FinalProject#1]
After creating entries in movies and books the database does not get written to the txt file properly.

**Comment by cpcharland** [comment]
What do you mean is isn't writing properly? Is it actually going into the file, or is it not writing to the file or what?

**Comment by jacbart** [comment]
any book or movie that i added while using the program didn't get added to the file after exiting.

**Comment by cpcharland** [comment]
Hmmm, but it creates the text file on close?

**Comment by jacbart** [comment]
the file was already there but yeah

**Comment by cpcharland** [comment]
Weird. I can't recreate that error. Try pulling the program down again?

**Comment by jacbart** [comment]
when I try to read the file it changes it to this
 "Movies
Up In the Air,Drama,-1,0
0,0,0,0
0,0,0,0
0,0,0,0
Books
The Hobbit,Fantasy,-1,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0"

**Comment by cpcharland** [comment]
Can you try the version that i just uploaded?

**Comment by jacbart** [comment]
the new one worked for me

**Comment by cpcharland** [comment]
Cool
